### ISSUE TITLE
是否显示缩略图选项

### ISSUE THREAD

**Issue by 5aaee9** [viosey/typecho-theme-material#1]
- 如果页面是图文混排的，在预览的时候会遮挡住正文什么的
- 而且如果取图片作为博文的前头的图片……距离太小并且个人感觉……比较丑

**Comment by iblh** [comment]
- 第一点目前唯一解决方案是通过加 `<!-- more -->` 截断符, 使得首页文章块只显示文字而不显示图片.
- 第二点的话目前计划增加文章块距离以及在后台可选是否显示缩略图.

**Comment by 5aaee9** [comment]
还有可以设置添加不要全文居中？看起来有点怪异

**Comment by iblh** [comment]
No problem!
