### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by akarineren** [viosey/typecho-theme-material#10]
首先 主题做的不错！

但是整个网站的布局和维护性还有提升 

开启 F12 随处可见的 `demo-blog-*` class名

整个网站在一个 div 中进行开发 毫无布局感

![image](http://ww4.sinaimg.cn/large/006clTSSgw1f3bnlfbytpj30b301rmxe.jpg)

希望 2.0 版本不要只是看上去简洁 内在也会重要 这难道不是你所追求的极客精神吗？

![geek](https://viosey.com/img/screenshot.jpg)

**Comment by iblh** [comment]
谢谢反馈, 2.0.0版会整理一遍代码的.

**Comment by iblh** [comment]
css 一开始用的是 Google 的源码, 开发时担心出 bug 所以也没有替换.
不可否认这是一项 "大工程", 我也会尽力在五一期间润色好css代码: )
