### ISSUE TITLE
默认主题时打开主页正常，切换您的主题的时候就会500 Database Query Error

### ISSUE THREAD

**Issue by Cettiidae** [viosey/typecho-theme-material#11]
[http://lyc.science/blog/](url)地址~

**Comment by Cettiidae** [comment]
主题名字已经更改，插件均禁用

**Comment by Cettiidae** [comment]
已经停止使用

**Comment by iblh** [comment]
[一脸懵逼]

可以的话请编辑 config.inc.php，在最后一行加上
`define('__TYPECHO_DEBUG__', true)`

方便查看错误日志呢
