### ISSUE TITLE
为什么新建的typecho，启用你的这个主题访问时返回500错误

### ISSUE THREAD

**Issue by CodeIdeal** [viosey/typecho-theme-material#12]
只提示Database Query Error
![](http://ww4.sinaimg.cn/large/a7eb544fgw1f47d1yuey6j20if05kjrc.jpg)

**Comment by iblh** [comment]
主题文件夹改名了吗？

**Comment by CodeIdeal** [comment]
改了啊
![](http://ww1.sinaimg.cn/large/a7eb544fgw1f48i7awb4uj207f0fo0tt.jpg)

**Comment by iblh** [comment]
切换其他主题, 再开启试试看?

**Comment by silenceu** [comment]
遇到了同样的错误

**Comment by CodeIdeal** [comment]
@SilenceU 你是不是后台数据库用的是 sqlite ，貌似是这个原因，你试试其他数据库看看。

**Comment by silenceu** [comment]
恩，已换mysql,可以使用了😇

**Comment by Aster-the-Med-Stu** [comment]
同样是MySQL，不能启用。

**Comment by sine-fandel** [comment]
我用的是mysql，但是还是出现同样的问题哦
