### ISSUE TITLE
打开某篇日志后屏幕左侧的back按钮无法使用

### ISSUE THREAD

**Issue by helijohnny** [viosey/typecho-theme-material#15]
在ios 9.3.2 中的safari和mac中的safari均可重现故障
而chrome中无此问题～～

**Comment by iblh** [comment]
thx~
那句 back 的 js 代码对 Safari 无效

**Comment by iblh** [comment]
我换一个试试看

**Comment by helijohnny** [comment]
谢谢，另外ios还有点击屏幕顶端无法回到页头的问题^_^

**Comment by iblh** [comment]
页面顶端确实有一些问题，比如在 Android Chrome 下，地址栏无法自动隐藏。

然后 back 按钮现在可以使用了 (已 commit) :)

> 不过在 Safari 确实还有几个 bug _(:з」∠)_

**Comment by helijohnny** [comment]
谢谢谢谢，主题做的非常漂亮！万分感谢

**Comment by iblh** [comment]
^_^
也谢谢你喜欢这个主题~
