### ISSUE TITLE
无法使用多说

### ISSUE THREAD

**Issue by n40k264** [viosey/typecho-theme-material#16]
Failed to load resource: the server responded with a status of 400 ({Bad Request})
dsembed.js:1 出错啦(990002): 参数错误
Failed to load resource: the server responded with a status of 400 ({Bad Request})
dsembed.js:1 出错啦(990002): 缺少站点信息

出现这2个错误。。 是不是我哪里设置错了。。

**Comment by iblh** [comment]
你是否有填入多说的 short_name 呢？

**Comment by n40k264** [comment]
嗯，有照说明填入short_name

**Comment by iblh** [comment]
以前遇见这个问题也是 short_name 的问题…
如果你是填对了的话，我就…不大清楚了

**Comment by n40k264** [comment]
好吧。。。我再看看。。
