### ISSUE TITLE
如何实现友情链接？

### ISSUE THREAD

**Issue by TrochilusGavin** [viosey/typecho-theme-material#18]
您好，我是该主题的用户，我看到有Links，但是后台管理似乎并没有友链，请问在该主题下如何实现友情链接呢？

**Comment by wangjh9712** [comment]
后台 - 管理 - 友情链接

**Comment by iblh** [comment]
楼上+1
（记得把友情链接的插件放上去）

**Comment by TrochilusGavin** [comment]
网上的Links插件资源貌似都用不成呢，求资源QAQ

**Comment by wangjh9712** [comment]
请**仔细**查看主题的使用方法  **https://github.com/viosey/typecho-theme-material#使用方法**
