### ISSUE TITLE
文章内容显示问题

### ISSUE THREAD

**Issue by neoFelhz** [viosey/typecho-theme-material#21]
文章中为什么不能显示粗体？是因为字体的原因吗？
我现在在用的版本是1.9.8-branch。

**Comment by neoFelhz** [comment]
还有，我用MarkDown语法中的bulleted llist，在文章内容中能不能把点显示出来？

**Comment by iblh** [comment]
(⊙o⊙) Branch 请选择 **master** 呀

无法粗体有可能是字体原因, 我稍后测试一下, 如果是这样的话会把字体更新 **(Branch: master)**
bulleted list 也会修复的

**Comment by neoFelhz** [comment]
好的，谢谢了！
如果有修复时在commit里注明一下，我到时候更新一下主题。
当时不选master是因为如果启用1.9.9会出现错误，所以退回去用1.9.8了。。。

**Comment by neoFelhz** [comment]
顺便问一下，这个图中的是现在主题文章引用的形式。
![](http://neofelhz.esy.es/images/00000003.png)
能不能改成下面图中这样的形式？我觉得这种引用的方式比较直观。。。
![](http://neofelhz.esy.es/images/00000002.png)

**Comment by neoFelhz** [comment]
好了，合并了最新的commit，粗体能够正常显示了。
非常感谢！

**Comment by iblh** [comment]
OK~
今天估计也会完成其他细节的修改
