### ISSUE TITLE
标题有时看不清

### ISSUE THREAD

**Issue by xcatliu** [viosey/typecho-theme-material#23]
标题是白字，如果背景图也是浅色就看不清了，比如你给的第二个截图。可以给图片加个黑色蒙层？或者文字黑色 text-border?

**Comment by xcatliu** [comment]
貌似实际的博客中是有黑色阴影的。

**Comment by iblh** [comment]
嗯嗯, 挺早之前就发现了这个问题后来 加阴影解决了 :-D
