### ISSUE TITLE
在Android版UC浏览器上首页排版有问题

### ISSUE THREAD

**Issue by atiAkizuki** [viosey/typecho-theme-material#24]
![image](https://o5yqq259o.qnssl.com/Screenshot_20160910-105806.png)

**Comment by neoFelhz** [comment]
UC的问题。我用他的主题，基于chromium的浏览器都可以正常使用。UC内核在网页排版上一向有问题。建议在手机上使用基于chormium内核或crosswalker内核的浏览器或者调用手机自带webview内核的套壳浏览器试试。

**Comment by atiAkizuki** [comment]
如果不打算给UC做适配的话，我就在nginx里检测一下UC的UA，然后让他们换个浏览器好了

**Comment by TechQuery** [comment]
@hxzchina @neoFelhz 

**UC 浏览器**、**腾讯 X5 内核** 都只支持 FlexBox 的最早版本，不光要设置相关属性，还要在 width、height 上有具体数值……

所以，对它们的兼容除了 [CSS 属性的合写](//git.oschina.net/Tech_Query/EasyWebUI/blob/1edcd35faad7bb28888f79f89e93cf70c4b2a92e/EasyWebUI.css#L643)，还要[用 JavaScript 做辅助计算](//git.oschina.net/Tech_Query/EasyWebUI/blob/1edcd35faad7bb28888f79f89e93cf70c4b2a92e/source/HTML-5_Patch/FlexBox.js)（我目前只做了伸展计算，没做收缩计算）~
