### ISSUE TITLE
加www或者不加www会导致排版错乱

### ISSUE THREAD

**Issue by ykla** [viosey/typecho-theme-material#28]
建议把所有绝对链接都改为相对链接。

**Comment by iblh** [comment]
有无 demo 查看一下?

**Comment by ykla** [comment]
已经发送邮箱

**Comment by iblh** [comment]
HTML 的文件看不了, 你可以发送线上 demo, 我主要是想看看是否报了什么错之类的, 因为我没有这样的配置所以如果有个线上测试会比较方便
