### ISSUE TITLE
一个罕见的小bug

### ISSUE THREAD

**Issue by neoFelhz** [viosey/typecho-theme-material#30]
我今天开启了https，并且更换了typecho的默认站点名。
但是再访问http的时候就会出现排版错误和有关资源找不到的问题。
虽然写好了跳转是没事了，但是有些浏览器禁止我这么跳转，会强制去浏览http。

**Comment by iblh** [comment]
我的跳转是写在 Nginx 里面, 然后也开了 HSTS, 似乎没有遇到浏览器禁止问题...
