### ISSUE TITLE
IIS+PHP7.0.10 提示 Trying to get property of non-object

### ISSUE THREAD

**Issue by love4taylor** [viosey/typecho-theme-material#34]
PHP Notice:  Trying to get property of non-object in E:\wwwroot\love4taylor\usr\themes\Material\functions.php on line 610

**Comment by iblh** [comment]
IIS 的环境我不是很清楚能否兼容

不过有个建议：
方便的话可以将博客迁移到 hexo

[Hexo-Theme-Material](https://github.com/viosey/hexo-theme-material)

原因有三：
1. Typecho 程序更新较慢，正式版仍是 14年版本
2. 由于 Hexo 开发自由度较高，我会比较偏向在 hexo 开发该主题 会提供更丰富的改进。
3. Hexo 的易用性，无论是什么环境，甚至是 Github 与 Coding 都可以部署。

**Comment by love4taylor** [comment]
恩 好哒
