### ISSUE TITLE
请求文章内容页有更好的阅读体验

### ISSUE THREAD

**Issue by KeJunMao** [viosey/typecho-theme-material#37]
文章内容嘛，阅读体验很重要，个人比较喜欢github的样式，而现在这个版本个人感觉体验不是很好。

Viosey可以参考这个[markdown编辑器](https://1024tools.com/markdown)生成的样式。

或者加个选项，切换文章页内容？

**尤其代码块**

**Comment by neoFelhz** [comment]
同要一个好一点的css样式。

我现在在用DT27的typecho编辑器插件Editor.MD自带的marked解析库（就是你给的链接的那个js）和prasedown解析库。他们输出的样式不错，但是不是有强制换行问题，就是把[]转义了（我有用播放器插件）。

我很喜欢作者博客《从alpha到2.0，从1到100》那篇的样式。

**Comment by iblh** [comment]
@neoFelhz Markdown 的渲染样式会做一个 Github 样式，有可能还有别的样式。

**Comment by neoFelhz** [comment]
好哒ヾ(Ő∀Ő๑)ﾉ
辛苦了nya。

**Comment by neoFelhz** [comment]
这个样式没准还是得我自己亲自操刀上了。。。

**Comment by neoFelhz** [comment]
很好，我自己弃坑了
