### ISSUE TITLE
关于pjax和引入pangu.js

### ISSUE THREAD

**Issue by neoFelhz** [viosey/typecho-theme-material#38]
1. 希望能实现评论区完整pjax无跳转（使用的是Typecho原生评论）
2. 希望引入Pangu.js，实现自动在中文和英文间加入半角空格。

**Comment by iblh** [comment]
1. 可以的话是会实现的，如果还没有实现的话就是遇到了一些问题
2. Pangu 可以考虑，后期应该会加上。

**Comment by neoFelhz** [comment]
1的话，原生评论中直接在文章后面回复，是不会发生跳转事件的；就是在回复中回复（嵌套回复）时会跳转一下。
多说的话不会跳转（但是我对多说不很放心，所以已经用回了原生评论。。。）
