### ISSUE TITLE
建议 - 首页及文章显示改进建议

### ISSUE THREAD

**Issue by tutu612** [viosey/typecho-theme-material#40]
~~1、建议增加  ”首页文章显示数“设定，
      以及”每篇文章在首页显示的字数限制“ 设定。~~

2、保证”继续阅读“字样能够在页面对齐，没办法强迫症23333

3、另外文章右上角的心型图标，始终带着红点，点击之后没有任何反应。。。

PS：使用Typecho 1.0.14.10.10.-release，XAMPP（PHP5.4.34），浏览器是Microsoft Edge。

谢谢大家的回复，以后一定仔细看readme ^_^

**Comment by neoFelhz** [comment]
1. 这个是在typecho里设置的。
2. 这个在文章里用实现即可，最多80。
3. 需要安装并启用有关插件

PS： TE建议使用开发版，可见减少很多bug。

**Comment by tutu612** [comment]
neoFelhz，十分感谢你的回复。
1、确实可通过插入实现对摘要字数的限制。
      但首页的摘要文字是没有任何格式的，无法像文章一样有换行，
      能否通过修改主题或Typecho，单独书写摘要文字用以控制排版？

2、分隔符仅能限制摘要文字数，但是遇到需要留白的情况，无法保证“继续阅读”在同一个位置。

3、求教插件是否为http://docs.typecho.org/plugins/download页面的 “Digg ”？

**Comment by neoFelhz** [comment]
- 1和2.是Typecho本身不支持
- 3的话请仔细阅读readme.md内的内容，已经提供了需要用的统计插件的下载地址。

**Comment by iblh** [comment]
1. typecho 如 @neoFelhz 所言既是。然后 hexo 版本可以自定义默认输出长度，并且可以通过 ` 来实现，优先级比默认输出高。
2. 请详阅 README.md 的内容。
