### ISSUE TITLE
底部footer有一小段会显示背景，建议底布添加博客运行时间的一栏

### ISSUE THREAD

**Issue by iibibi** [viosey/typecho-theme-material#45]
底部有一小段会显示背景。
建议底布添加一个博客允许时间。

**Comment by iblh** [comment]
方便贴一下图片吗？

运行时间可以有

**Comment by iibibi** [comment]
![](https://nzsg3jhu3.qnssl.com/87xiltn4zjq1zotag5bfbt9.jpg)
大概就是这样 2.0.0的版本貌似没有这个bug，手机版的背景图在页面滑到底部时大小会改变

**Comment by iibibi** [comment]
在主题归档中。如果没有足够的文章（新博客）。。。。底部会跑到上面去。

**Comment by iblh** [comment]
对的... 这是一个历史遗留问题

这个 issue 先 open，或许会修复的

**Comment by iibibi** [comment]
可不可以再加入一个音乐播放器了。
QPlayer挺不错的。
可不可以把他集成到主题里呢？
最好支持Pjax。无间断的播放。

**Comment by neoFelhz** [comment]
Qplayer 的话，有个问题就是这个主题的 Pjax 容器刚好没有包括 Qplayer 。需要的话可以自己修改 Typecho 的源码，修改插件的加载顺序和位置。

**Comment by iibibi** [comment]
@neoFelhz  可以具体一点吗？

**Comment by neoFelhz** [comment]
- Qplayer 加载这个我得再回去看看 Typecho 的源码
- 文章底部显示运行时间我已经修改好了，Viosey 大大也已经合并了，更新一下试试？

**Comment by iibibi** [comment]
@neoFelhz 好的。
