### ISSUE TITLE
多说bug

### ISSUE THREAD

**Issue by cmsax** [viosey/typecho-theme-material#46]
在一个文章下面的 评论/点赞 会被应用到每一个文章。

**Comment by iblh** [comment]
https://material.vss.im/services/#duoshuo

建议看一下这个文档，使用多说需要在文章中加上独立的 id

**Comment by cmsax** [comment]
请问有快捷方法让id=title么？

**Comment by iblh** [comment]
现在需要手动修改一下，
在 `主题文件夹` 下 `layout` -> `_widget` -> `duoshuo.ejs` 中，
找到 `<%= page.id %>` 替换为 `<%= page.title %>`

**Comment by iblh** [comment]
对了，你是使用 typecho 还是 hexo？
没注意看，以为你用的是 hexo，上面那条是针对 hexo 的。

如果你使用的是 typecho，麻烦告知你的博客链接，我去看看

**Comment by cmsax** [comment]
是hexo~

**Comment by iblh** [comment]
这个 issue 开错地方了😂
[hexo-theme-material](https://github.com/viosey/hexo-theme-material)
