### ISSUE TITLE
无法滚动

### ISSUE THREAD

**Issue by TChenQuan** [viosey/typecho-theme-material#49]
http://www.illn.in/

找不出原因了 OAQ 特来求助

**Comment by iblh** [comment]
[Mac 实测视频](https://qiniu.viosey.com/mp4/2016111921illnin.mp4) 没毛病呀

**Comment by neoFelhz** [comment]
看起来像是你用的 Hikoto API 或者是我引用的来自 CloudFlareCDN 的 pangu.min.js 拖慢了网站加载速度导致的（因为你既然在用香港的主机，速度应该不会太慢的）

**Comment by neoFelhz** [comment]
把 footer.php 里引用的 pangu.min.js 的源换成 https://cdn.bootcss.com/pangu/3.2.1/pangu.min.js 试试？
Hikoto API 也可以试着换成 lwl12 或者萨摩公园的源。
