### ISSUE TITLE
大佬，有点问题~

### ISSUE THREAD

**Issue by Moehentai2333** [viosey/typecho-theme-material#56]
首先是电脑端打开时右边下拉条有时会蜜汁消失
还有就是移动端打开时，左上角的那个显示异常
本鹅的博客：https://blog.conoha.vip

**Comment by iblh** [comment]
我这边看是木有问题的，可以截个图放粗来看看

**Comment by Moehentai2333** [comment]
https://pan.baidu.com/s/1hsA1ilA
左上角，好别扭，原本就是这样的嘛ヽ(•̀ω•́ )ゝ
还有，大佬，ty到底用什么smtp插件，找了好久没找到( ´Д｀)y━・~~

**Comment by iblh** [comment]
Typecho 现在的版本是有一个框框（Hexo 则没有框框）。
BTW，我现在已经转移到 hexo 了，若要获得 LTS 的话 建议也迁移到 hexo。
Typecho 差不多已经弃坑了。
SMTP 的话我也不大清楚了_(:з」∠)_

**Comment by neoFelhz** [comment]
SMTP 基本上取决于你的主机是否阉割了邮箱功能（我的主机就没有）。
我在用 Typecho 时用了 `评论邮箱提醒插件` 和 `忘记密码找回` 插件，用的都是 PHP 函数。
