### ISSUE TITLE
移动端左侧按钮显示问题

### ISSUE THREAD

**Issue by yorkchou92** [viosey/typecho-theme-material#63]
浏览器：safari，chrome；系统：iOS 10.2.1
左侧按钮“Sidebar hamburger button”会产生边框
![img_3056 20170225-135328](https://cloud.githubusercontent.com/assets/24680809/23328658/e97e584a-fb61-11e6-8815-5c0e3ea70b21.jpg)
————————————————————
2017-03-01 update:
呃，好像边框是有意为之的？但是边框会错位。
另外我看hexo版本无边框，所以提出这个issue，还望见谅哈~

**Comment by ghost** [comment]
我也发现了，不过如果横屏显示的话 又没有边框了。

**Comment by iblh** [comment]
是的，这是曾经作为 A/B Test 的一个设计，后来便在 hexo 版本移除。
但因为 typecho 已经停止更新，所以此设计仍然遗留。
