### ISSUE TITLE
页面底部有空隙

### ISSUE THREAD

**Issue by yorkchou92** [viosey/typecho-theme-material#64]
页面底部的footer，不知为何没能顶住最底边，仍旧有一些空隙。
![buttom](https://cloud.githubusercontent.com/assets/24680809/23449919/746927bc-fe93-11e6-8226-4c33759243ac.jpg)

**Comment by monsterxcn** [comment]
23333你只要把 footer 高度调大一点就遮住了

**Comment by neoFelhz** [comment]
typecho-theme-material stop support since Final Release.
