### ISSUE TITLE
又拍云logo

### ISSUE THREAD

**Issue by RaingoTop** [viosey/typecho-theme-material#71]
能不能换到页脚？

**Comment by neoFelhz** [comment]
不能。
请直接电子邮件 又拍云联盟，可完成验证。

**Comment by RaingoTop** [comment]
你好，我曾尝试申请又拍云，但是审核时貌似没注意侧边栏的logo，未通过

**Comment by neoFelhz** [comment]
@RaingoTop 
我说了，请直接给又拍云联盟发送电子邮件声明情况后即可申请成功。
