### ISSUE TITLE
关于评论框

### ISSUE THREAD

**Issue by MeowCold** [viosey/typecho-theme-material#8]
感觉评论少了到没什么，评论多了感觉单条评论占的面积好大。请问有吧头像和评论平齐的想法吗？
对了在你的博客里主题文章页面留言总提示未填写名称 邮箱 留言

**Comment by iblh** [comment]
@MeowCold 
谢谢反馈~ 
评论的样式会进一步优化.

---

然后留言默认是需要填写名称与邮箱的, 这个是typecho自带的设定

**Comment by MeowCold** [comment]
@viosey 额我都输入了

**Comment by iblh** [comment]
@MeowCold 
噢 sorry, 这个bug已经修复了, 欢迎评论喔 :)

**Comment by MeowCold** [comment]
嗯嗯
